name: Do a Duolingo lesson

on:
  schedule:
    - cron: '0 0-23 ? * *'  # Runs several times daily at random hours (0-23)

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Upgrade to version 5 for outputs support

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: generate_lessons
        run: |  # Multi-line script with temporary variable
          lesson_count=$((RANDOM % 11)) + 10
          echo "##@variables:lessons=$lesson_count"

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ steps.generate_lessons.env.lessons }}
