name: Do a Duolingo lesson

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: generate_lessons
        run: |  # Multi-line script with temporary variable
          lesson_count=$(( (RANDOM % 13) + 3 ))
          echo "lessons=$lesson_count" >> $GITHUB_ENV
          echo "Generated lesson count: $lesson_count"

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ env.lessons }}
